### ISSUE TITLE
Does not match GitHub URL pattern. It's not working on enterprise github with two private repos

### ISSUE THREAD

**Issue by ZhUyU1997** [webfactory/ssh-agent#112]
I tried to config two private keys on enterprise Github. 
But something is wrong with it.
```sh
Comment for (public) key 'ssh-ed25519 xxxxgit@github.sec.samsung.net:aaaa.git' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
Comment for (public) key 'ssh-ed25519 xxxxgit@github.sec.samsung.net:bbbb.git' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```
Can we support config Github hostname?

Thanks,
Yu Zhu

**Comment by Smarker** [comment]
This issue is also super similar to https://github.com/webfactory/ssh-agent/issues/123

**Comment by mpdude** [comment]
> This issue is also super similar to #123

To my understanding, #123 is about an unnecessary (meaningless) log output line due to a parsing glitch.

**Comment by mpdude** [comment]
Yes. The problem is that we need to recognize the different repo names, set up fake hostnames for them, then map those back to the right ones while specifying the key in the SSH config and finally make git rewrite differnt variants of the original URL to the replacement hosts... 🥴.

If anyone comes up with a good suggestion how to make this work for repo URLs in general (i. e. not limited to the git@github.com/org/repo pattern), I'd be happy to discuss that!

**Comment by mpdude** [comment]
There are duplicate reports for this. I've created #128 to focus the discussion in one issue.
