### ISSUE TITLE
Multiple SSH keys not working on GitHub Enterprise

### ISSUE THREAD

**Issue by lcmgh** [webfactory/ssh-agent#117]
Hi!
  
I followed the docs to setup multiple ssh keys by generating them with comment parameter `-C` and adding the git URL from my GitHub Enterprise repo.

`https://private-github.myenterprise/org/repo.git`

I ensured correct keys were set as secret and deploy key but it seems correct keys are not mapped.

```
    - uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key:  |
            ${{ secrets.DEPENDENCY_ACCESS_2 }}
            ${{ secrets.DEPENDENCY_ACCESS_2 }}
```

ERROR: Permission to abc denied to deploy key
  fatal: Could not read from remote repository.

Might it be because only github.com URLs are supported? https://github.com/webfactory/ssh-agent/blob/dc622c59e471395a5b1e0d96279fe835c87a218b/index.js#L67

Thanks

**Comment by mpdude** [comment]
Yes. The problem is that we need to recognize the different repo names, set up fake hostnames for them, then map those back to the right ones while specifying the key in the SSH config and finally make `git` rewrite differnt variants of the original URL to the replacement hosts... 🥴.

If anyone comes up with a good suggestion how to make this work for repo URLs in general (i. e. not limited to the `git@github.com/org/repo` pattern), I'd be happy to discuss that!

**Comment by mpdude** [comment]
This is the same as #112, let's discuss it over there.
