### ISSUE TITLE
passphrase support

### ISSUE THREAD

**Issue by tcurdt** [webfactory/ssh-agent#36]
> Make sure you don't have a passphrase set on the private key.

Any thoughts on adding support keys with passphrases?

**Comment by mpdude** [comment]
Why would that make sense?

**Comment by tcurdt** [comment]
Given that in this case it is just another env variable - little.

Nevertheless they are common - at least in the interactive world.
And some environments even require them.

I personally think it would probably make more sense to tighten the security (for that user/key) on the server instead. But that's beyond the scope of this issue.

**Comment by mpdude** [comment]
I think you should not use your "interactive" key for GH Actions, but use a dedicated key.

The passphrase is not an additional security measure at the server side, but it's used to encrypt the key before it is stored on disk. Since this action recommends using Action Secrets to store the key, it does not make sense to me to store an encrypted key but then use another secret to hold the key passphrase.

If you already have a key with a passphrase, you can also remove it with `ssh-keygen`. 

WDYT?

**Comment by tcurdt** [comment]
I definitely should be a different key - that is without question.

In the case of github actions I guess I agree, it really does not make much sense as both would be passed in as env variables.

I think I will have to go another way anway. Sorry for the noise :)
